spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:emaildb}
    username: ${DB_USER:admin}
    password: ${DB_PASS:Password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:your_email@gmail.com}
    password: ${SMTP_PASS:Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:Password}

server:
  port: ${PORT:8080}

app:
  queue-name: email_queue

logging:
  level:
    root: INFO
